export const ADD_TASK = 'ADD_TASK'
export const REMOVE_TASK = 'REMOVE_TASK'
export const CHANGE_TASK = 'CHANGE_TASK'
export const HANDLE_TASK = 'HANDLE_TASK'
export const SUBMIT_CHANGE_TASK = 'SUBMIT_CHANGE_TASK'
export const RESET_EDIT = 'RESET_EDIT'
